[package]
name = "worldql_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
tmq = "0.3.0"
tokio-postgres = "0.7.4"
log = "0.4.14"
env_logger = "0.9.0"
uuid = { version = "0.8", features = ["v4"] }
flatbuffers = "2.0.0"
flexbuffers = "2.0.0"