[package]
name = "worldql_server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
flatbuffers = "2.0.0"
thiserror = "1.0.30"
tokio = { version = "1.12.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
