[package]
name = "worldql_server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
color-eyre = "0.5.11"
derive-getters = "0.2.0"
flatbuffers = "2.0.0"
futures-util = "0.3.17"
portpicker = "0.1.1"
rand = "0.8.4"
scopeguard = "1.1.0"
thiserror = "1.0.30"
tmq = { version = "0.3.0", optional = true, features = ["zmq-vendored"] }
tokio = { version = "1.13.0", features = ["full"] }
tokio-postgres = "0.7.5"
tokio-tungstenite = { version = "0.15.0", optional = true }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
uuid = { version = "0.8.2", features = ["v4"] }

[features]
default = ["zeromq", "websocket"]
zeromq = ["tmq"]
websocket = ["tokio-tungstenite"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
